#production
deployment:
    user: example
    from: ./
    to: /home/example/public_html/production
    scm:
        branch: master
    excludes:
        - .idea
        - .mage
        - ._*
        - .DS_Store
        - .gitignore
        - phpunit.*
        - bootstrap.php
        - ^app/cache
        - ^app/config/parameters.yml
        - ^app/logs
        - ^assets
        - ^files
        - ^images
        - ^system/logs
        - ^system/modules
        - ^system/themes
        - ^vendor
        - ^web/assets
        - ^web/bundles
        - ^web/files
        - ^web/share
        - ^web/system
        - ^web/layout/styles
        - ^web/layout/scripts
        - ^web/install.php
        - ^web/app_dev.php

releases:
    enabled: true
    max: 5
    symlink: current
    directory: releases

hosts:
    - example.com

tasks:
    pre-deploy:
        - build-styles
        - build-scripts
        - unit-tests
    on-deploy:
        - filesystem/link-shared-files:
            linked_files:
                - app/config/parameters.yml: relative
            linked_folders:
                - app/logs: relative
                - files: relative
                - images: relative
        - composer/install: {dev: false}
        - composer/generate-autoload
        - symfony2/cache-warmup: {env: prod}
        - symfony2/assets-install: {env: prod, symlink: true, relative: true}
        - contao-install
        - maintenance-lock
    post-release:
        - symfony2/doctrine-migrate: {env: prod}
        - doctrine-clear: {env: prod}
        - symfony2/cache-clear: {env: prod}
        - maintenance-unlock
