magephp:
    log_dir: ./.mage_logs
    composer: { path: 'php71 /home/%USERNAME%@/public_html/composer.phar' }
    symfony: { console: 'php71 ./vendor/bin/contao-console' }
    # Deploy using gnu tar!
    exclude:
        - ._*
        - .DS_Store
        - ./.idea
        - ./.mage_logs
        - ./app/config/parameters.yml
        - ./app/Resources/contao/config/runonce*
        - ./assets
        - ./files
        - ./layout
        - ./node_modules
        - ./system
        - ./tests
        - ./var
        - ./vendor
        - ./web/assets
        - ./web/bundles
        - ./web/files
        - ./web/share
        - ./web/system
        - ./web/.htaccess.production
        - ./web/app.php
        - ./web/install.php
        - ./.babelrc
        - ./.eslintrc.json
        - ./.gitignore
        - ./.mage.yml
        - ./gulpfile.js
        - ./package.json
        - ./package-lock.json
        - ./phpunit.*
        - ./README.md
        - ./composer.json~

    environments:

        # Development
        development:
            user: %USERNAME%
            host_path: /home/%USERNAME%/public_html
            releases: 3
            hosts:
                - %HOSTNAME%
            symfony: { env: 'dev' }
            tar_create_path: gtar
            pre-deploy:
                - Terminal42\MageTools\Task\IntegrityCheck\ContaoTask: { console: './vendor/bin/contao-console' }
                - exec: { cmd: './node_modules/.bin/gulp', desc: 'Running Gulp' }
            on-deploy:
                - composer/self-update
                - exec: { cmd: 'mkdir assets && mkdir system && mkdir var && mkdir -p web', desc: 'Creating initial directories' }
                - fs/link: { from: '../../../../shared/config/parameters.yml', to: 'app/config/parameters.yml' }
                - fs/link: { from: '../../../shared/config', to: 'system/config' }
                - fs/link: { from: '../../../shared/images', to: 'assets/images' }
                - fs/link: { from: '../../shared/files', to: 'files' }
                #- fs/link: { from: '../../shared/templates', to: 'templates' }
                - fs/link: { from: '../../../shared/logs', to: 'var/logs' }
                - fs/link: { from: '../../../shared/share', to: 'web/share' }
                - fs/move: { from: 'web/.htaccess.development', to: 'web/.htaccess' }
                - Terminal42\MageTools\Task\Symfony\PlatformReleaseTask
                - composer/install: { timeout: 600 }
                - fs/move: { from: 'web/app_dev.php', to: 'web/app.php' }
                - Terminal42\MageTools\Task\Maintenance\LockTask
            on-release:
                - Terminal42\MageTools\Task\Symfony\AcceleratorCacheClearTask
            post-release:
                - Terminal42\MageTools\Task\Doctrine\MigrateTask
                - Terminal42\MageTools\Task\Maintenance\UnlockTask
                - deploy/release/cleanup

        # Production
        production:
            user: %USERNAME%
            branch: master
            host_path: /home/%USERNAME%/public_html
            releases: 3
            hosts:
                - %HOSTNAME%
            symfony: { env: 'prod' }
            tar_create_path: gtar
            pre-deploy:
                - 'Terminal42\MageTools\Task\IntegrityCheck\ContaoTask': { console: './vendor/bin/contao-console' }
                - exec: { cmd: './node_modules/.bin/encore prod', desc: 'Running Symfony Encore' }
            on-deploy:
                - composer/self-update
                - exec: { cmd: 'mkdir assets && mkdir system && mkdir var && mkdir -p web', desc: 'Creating initial directories' }
                - fs/link: { from: '../../../../shared/config/parameters.yml', to: 'app/config/parameters.yml' }
                - fs/link: { from: '../../../shared/config', to: 'system/config' }
                - fs/link: { from: '../../../shared/images', to: 'assets/images' }
                - fs/link: { from: '../../shared/files', to: 'files' }
                #- fs/link: { from: '../../shared/templates', to: 'templates' }
                - fs/link: { from: '../../../shared/logs', to: 'var/logs' }
                - fs/link: { from: '../../../shared/share', to: 'web/share' }
                - fs/move: { from: 'web/.htaccess.production', to: 'web/.htaccess' }
                - Terminal42\MageTools\Task\Symfony\PlatformReleaseTask
                - composer/install: { timeout: 600 }
                - Terminal42\MageTools\Task\Maintenance\LockTask
            on-release:
                - Terminal42\MageTools\Task\Symfony\AcceleratorCacheClearTask
            post-release:
                - Terminal42\MageTools\Task\Doctrine\MigrateTask
                - Terminal42\MageTools\Task\Maintenance\UnlockTask
                - deploy/release/cleanup
