
contao:
    prepend_locale: true
    localconfig:
        licenseAccepted: true
        enableSearch: false
        disableCron: true

        installPassword: "%install_password%"
        websiteTitle: ~
        adminEmail: ~
        dateFormat: "d.m.Y"
        datimFormat: "d.m.Y H:i"
        timeZone: 'Europe/Zurich'

        # Adjust the upload image settings
        maxFileSize: 20480000
        imageWidth: 2500
        imageHeight: 2500

doctrine_migrations: ~

accelerator_cache:
    host: "%platform_host%"
    web_dir: "%kernel.root_dir%/../web"

imports:
#    - { resource: orm.yml }
    - { resource: services.yml }
