# Doctrine ORM configuration
doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.default
        auto_mapping: true

        metadata_cache_driver:
            type: service
            id: doctrine_cache.providers.doctrine_metadata_cache
        result_cache_driver:
            type: service
            id: doctrine_cache.providers.doctrine_result_cache
        query_cache_driver:
            type: service
            id: doctrine_cache.providers.doctrine_query_cache

doctrine_cache:
    providers:
        doctrine_metadata_cache:
            file_system:
                extension: ".cache"
                directory: "%kernel.cache_dir%/doctrine/metadata"
        doctrine_result_cache:
            file_system:
                extension: ".cache"
                directory: "%kernel.cache_dir%/doctrine/result"
        doctrine_query_cache:
            file_system:
                extension: ".cache"
                directory: "%kernel.cache_dir%/doctrine/query"
