
contao:
    prepend_locale: true
    localconfig:
        licenseAccepted: true
        enableSearch: false
        disableCron: true
        folderUrl: false

        installPassword: '%env(INSTALL_PASSWORD)%'
        adminEmail: '%env(ADMIN_EMAIL)%'
        dateFormat: 'd.m.Y'
        datimFormat: 'd.m.Y H:i'
        timeZone: 'Europe/Zurich'

        # Adjust the upload image settings
        maxFileSize: 20480000
        imageWidth: 2500
        imageHeight: 2500

framework:
    secret: '%env(APP_SECRET)%'
    assets:
        json_manifest_path: '%kernel.project_dir%/web/layout/manifest.json'

doctrine:
    dbal:
        connections:
            default:
                url: '%env(DATABASE_URL)%'

doctrine_migrations: ~

accelerator_cache:
    host: '%env(APP_HOST)%'
    web_dir: '%kernel.root_dir%/../web'

imports:
    - { resource: services.yml }
